### ISSUE TITLE
one email is register to many times 

### ISSUE THREAD

**Issue by Nitthishri-0104** [barathcharm/ProPlan-Project#3]
### Description of issue

one email is registering to many times 

### Expected result

one email is sign in only one times

### Actual result

one email is registering to several times.

### Steps to reproduce
1. 
2. 
3. 

```
Path:      /assests/pages/login.html
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 860 @1.5x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--pro-plan.netlify.app%2Fassests%2Fpages%2Flogin.html&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x860&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--pro-plan.netlify.app/assests/pages/login.html)

**Comment by barathmohan05** [comment]
Resolved  this issue..!
