### ISSUE TITLE
password validation in login and  signup page

### ISSUE THREAD

**Issue by Nitthishri-0104** [barathcharm/ProPlan-Project#4]
### Description of issue

form is submitting if I give the 3 digits .

### Expected result

password atleast contain uppercase , lowercase  and number

### Actual result

Atleast 5 digits is necessary for the password for submitting the form

### Steps to reproduce
1. 
2. 
3. 

```
Path:      /assests/pages/login.html
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1671 x 955 @1.3499999046325684x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--pro-plan.netlify.app%2Fassests%2Fpages%2Flogin.html&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1671x955&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--pro-plan.netlify.app/assests/pages/login.html)

**Comment by barathmohan05** [comment]
Resolved the issue..!
