### ISSUE TITLE
login page input box is not working

### ISSUE THREAD

**Issue by Nitthishri-0104** [barathcharm/ProPlan-Project#5]
### Description of issue
when I type the value inside the input box  and click the submit button ,again the input box become empty and not working

### Expected result
login page want to work properly when I login 

### Actual result
login page is not working properly

### Steps to reproduce
1. 
2. 
3. 

```
Path:      /assests/pages/login.html
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1671 x 575 @1.3499999046325684x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--pro-plan.netlify.app%2Fassests%2Fpages%2Flogin.html&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1671x575&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--pro-plan.netlify.app/assests/pages/login.html)

**Comment by barathmohan05** [comment]
resolved the issue..!
